source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
#use_frameworks!

inhibit_all_warnings!

link_with 'app', 'appTests'

def import_pods
    pod 'XMLDictionary'
    pod 'Regexer'
    pod 'Bolts'



    pod 'SDWebImage'
    pod 'AFNetworking'    

#    pod 'SWRevealViewController'
#    pod 'ISMemoryCache'
#    pod 'EGOCache'

    # pod 'SQPersist'

    # pod 'pop'
    # pod 'AsyncDisplayKit'

    pod 'Google-API-Client/YouTube'

    pod 'CHTCollectionViewWaterfallLayout'

    pod 'IGYouTubeExtractor'

  # ________________project library___________________
  pod "App_Module_Resources", :path => "../modules/App_Module_Resources"
  pod "YouTubeAPI3-Objective-C-wrapper", :path => "../modules/YouTubeAPI3-Objective-C-wrapper"

  #pod "WPMoviePlayerController", :path => "../dependencies/WPMoviePlayerController"

  #pod "YKMediaPlayerKit", :path => "../dependencies/YKMediaPlayerKit"
  #pod "MPMoviePlayerController-Subtitles", :path => "../dependencies/MPMoviePlayerController-Subtitles"

  
  

end

target 'app', :exclusive => true do
  # ________________common tools library___________________
  import_pods

  pod  'Reveal-iOS-SDK'

end


target 'appTests', :exclusive => true do
  import_pods

    #pod 'Expecta'
    #pod 'OCMock'
    #pod 'OCMockito'



end
