source 'https://github.com/CocoaPods/Specs.git'

platform :ios, 7.0

inhibit_all_warnings!

target 'AsYoutubeiPadSwiftClient', :exclusive => true do
  # ________________common tools library___________________

  pod 'XMLDictionary'
  pod 'Regexer'
  pod 'Bolts'
  pod 'SDWebImage'
  pod 'AFNetworking'
  pod 'SWRevealViewController'
  pod 'ISMemoryCache'
  pod 'EGOCache'
  pod 'SQPersist'

  pod 'AsyncDisplayKit'

  pod 'Google-API-Client'

end
